travis:
  secure:
    BINSTAR_TOKEN: E/X7o5/BYZlqIJvGHeoVKhwVl1fkIHMk6/d0/SFwpH+p9nLG6GUsrlaEmkbalCwqx0wjYLw0fGerq7QW8yjRZwpXgKEq7ColWiHNe2SDZlws0rCTLZgoWRcCql57N9me2O8ZVak4kdVRPlP0LRhUwmXSXiDkPTxyqRarPGtMQyYdTdyqvIw4f97bGuR4mV2+BOYISfs1r6IUxAd06klxzUIPKTFqaI2BiNRvT98Fg9BM9KfuCOOfwOoyXn+Zj+j+FUYPgwF6Ziz0E/WIM6PgFSTzLWS2Iy0jFz39FkHsz/QDyR6vkvOtmrQqrh0ujzZmQJQOKeJRD3zHTLgjsdy0dFlukXgfpMwM3nDgQYYiUsOw1dQWW8wtqydMsWoWhj86qY0sXDmSVfL25ul7kNOFTs7UmV+p5hNV3zMK+jDaNmPkEhCQXJgQTkeM3abYfnXtpvxDBVKGnuMu5mJXD2u45QOdcQOMTvIVWFOGR6HxflkhdOlzGr+iYuUN6QsSkkKz9VjFB2uRqJfjwVhKb6XhDxumVFKHBGB6T9BrMx5c2YzLffm413aGiO5fIrQeijKVkI7fTI8gLjNVya0P76L3ZYPdbvP0F8a88knynwFH4QYOoFiww09zsYlyxLOBRAMgqSjZ8Wb7vtkcbwME4Gi5lGgcUcsh9qwQTAX3AmJj4Y0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
